# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
    ]
