# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import karmin.giftcards.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftcards', '0002_auto_20170803_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcard',
            options={'verbose_name': 'Подарункова Картка', 'verbose_name_plural': 'Подарункові Картки'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажа картки', 'verbose_name_plural': 'Продажи карток'},
        ),
        migrations.AddField(
            model_name='giftcard',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.BigIntegerField(unique=True, validators=(karmin.giftcards.models.maximum_10_symbols,), verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створений'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='value',
            field=models.PositiveIntegerField(choices=[(50, '50₴'), (100, '100₴'), (200, '200₴'), (500, '500₴')], verbose_name='Вартість'),
        ),
    ]
